<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>awk</string>
	</array>
	<key>name</key>
	<string>AWK</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#procedure</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pattern</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtin-pattern</key>
		<dict>
			<key>match</key>
			<string>\b(BEGINFILE|BEGIN|ENDFILE|END)\b</string>
			<key>name</key>
			<string>constant.language.awk</string>
		</dict>
		<key>command</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:next|print|printf)\b</string>
					<key>name</key>
					<string>keyword.other.command.awk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:close|getline|delete|function|system)\b</string>
					<key>name</key>
					<string>keyword.other.command.nawk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:fflush|nextfile)\b</string>
					<key>name</key>
					<string>keyword.other.command.bell-awk</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.awk</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp-constant</string>
				</dict>
			</array>
		</dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\(?:[\\abfnrtv/"]|x[0-9A-Fa-f]{2}|[0-7]{3})</string>
			<key>name</key>
			<string>constant.character.escape.awk</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:exp|int|log|sqrt|index|length|split|sprintf|substr)\b</string>
					<key>name</key>
					<string>support.function.awk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:atan2|cos|rand|sin|srand|gsub|match|sub|tolower|toupper)\b</string>
					<key>name</key>
					<string>support.function.nawk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:gensub|strftime|systime)\b</string>
					<key>name</key>
					<string>support.function.gawk</string>
				</dict>
			</array>
		</dict>
		<key>function-definition</key>
		<dict>
			<key>begin</key>
			<string>\b(function)\s+(\w+)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.awk</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.awk</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.awk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(\w+)\b</string>
					<key>name</key>
					<string>variable.parameter.function.js</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(?:break|continue|do|while|exit|for|if|else|return)\b</string>
			<key>name</key>
			<string>keyword.control.awk</string>
		</dict>
		<key>numeric-constant</key>
		<dict>
			<key>match</key>
			<string>\b[0-9]+(?:\.[0-9]+)?(?:e[+-][0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.awk</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:[\+\-*/%}^&lt;&gt;!=]|\*\*)=?|[|&amp;+-]{2}|~!|\[|\]?</string>
					<key>name</key>
					<string>keyword.operator.awk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.nawk</string>
				</dict>
			</array>
		</dict>
		<key>pattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#builtin-pattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-definition</string>
				</dict>
			</array>
		</dict>
		<key>procedure</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#procedure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>regexp-constant</key>
		<dict>
			<key>begin</key>
			<string>/</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.start.awk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.regex.end.awk</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<key>string-constant</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.awk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.awk</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.awk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$[0-9]+</string>
					<key>name</key>
					<string>variable.language.awk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:FILENAME|FS|NF|NR|OFMT|OFS|ORS|RS)\b</string>
					<key>name</key>
					<string>variable.language.awk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:ARGC|ARGV|CONVFMT|ENVIRON|FNR|RLENGTH|RSTART|SUBSEP)\b</string>
					<key>name</key>
					<string>variable.language.nawk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:ARGIND|ERRNO|FIELDWIDTHS|IGNORECASE|RT)\b</string>
					<key>name</key>
					<string>variable.language.gawk</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.awk</string>
	<key>uuid</key>
	<string>67bd1ff0-006b-4c32-8b97-8bc198777582</string>
</dict>
</plist>
